[package]
name = "seatd"
version = "0.9.3"
description = "A minimal seat management daemon, and a universal seat management library" 
source = "https://git.sr.ht/~kennylevinsen/seatd/archive/0.9.3.tar.gz"

[build]
system = "meson"
