[package]
name = "neovim"
version = "0.12.5"
description = "Vim-fork focused on extensibility and usability"
source = "https://github.com/neovim/neovim/archive/refs/tags/v0.12.5.tar.gz"

[build]
system = "manual"
build_commands = [
	'sed -i "s/prop->ambiguous_width/0/g" src/nvim/mbyte.c',
	'mkdir build',
	'cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release',
	'make -C build -j$RAD_CORES'
]
install_command = "make install -C build"
depends = "luv,libtermkey,unibilium,libvterm"
