[package]
name = "cef-bin"
version = "6533"
description = "Chromium Embedded Framework (binary build from Spotify CDN)"
source = "https://cdn-fastly.obsproject.com/downloads/cef_binary_6533_linux_x86_64.tar.xz"

[build]
system = "manual"
build_commands = [
	"true"
]
install_command = [
	"mkdir -p $DESTDIR/opt/cef && cp -r ./* $DESTDIR/opt/cef/"
]
