[package]
name = "libinput"
version = "1.32.0"
description = "Input device management and event handling library"
source = "https://gitlab.freedesktop.org/libinput/libinput/-/archive/1.32.0/libinput-1.32.0.tar.gz"

[build]
system = "meson"
depends = [
	"libwacom",
	"libevdev"
]
