[package]
name = "plog"
version = "1.1.11"
description = "Portable, simple and extensible C++ logging library"
source = "https://github.com/SergiusTheBest/plog/archive/refs/tags/1.1.11.tar.gz"

[build]
system = "manual"
depends = "cmake"
build_commands = [
	"cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr",
	"cmake --build build"
]
install_command = "DESTDIR=$DESTDIR cmake --install build"
