[package]
name = "gzip"
version = "1.14"
description = "The Gzip package contains programs for compressing and decompressing files"
source = "https://ftpmirror.gnu.org/gzip/gzip-1.14.tar.xz"

[build]
system = "autotools"
