[package]
name = "qtwayland"
version = "6.11.2"
description = "Qt 6 Wayland platform plugin and module"
source = "https://download.qt.io/official_releases/qt/6.11/6.11.2/submodules/qtwayland-everywhere-src-6.11.2.tar.xz"

[build]
system = "cmake"
depends = "qtbase"
configure_args = [
	"-DCMAKE_INSTALL_PREFIX=/usr",
	"-DCMAKE_INSTALL_LIBDIR=lib",
	"-DCMAKE_BUILD_TYPE=Release",
    	"-DQT_BUILD_EXAMPLES=OFF",
    	"-DQT_BUILD_TESTS=OFF",
	"-DFEATURE_wayland_client=ON"
]

