[package]
name = "linux"
version = "7.1.6"
description = "The Linux package contains the Linux kernel"
source = "https://www.kernel.org/pub/linux/kernel/v7.x/linux-7.1.6.tar.xz"

[build]
system = "manual"
build_commands = [
	"make mrproper",
	"cp /var/lib/rad/packages/config/linux .config",
	"make menuconfig",
	"make -j$RAD_CORES"
]
install_command = [
	"mkdir -p $DESTDIR/boot $DESTDIR/var/lib/rad/packages/config $DESTDIR/usr/src/linux-7.1.6 $DESTDIR/lib/modules/7.1.6",
	"make modules_install INSTALL_MOD_PATH=$DESTDIR",
	"cp arch/x86/boot/bzImage $DESTDIR/boot/vmlinuz-7.1.6-radian",
	"make headers_install INSTALL_HDR_PATH=$DESTDIR/usr",
	"cp -r * $DESTDIR/usr/src/linux-7.1.6/",
	"rm -rf $DESTDIR/lib/modules/7.1.6/build || true",
	"ln -s /usr/src/linux-7.1.6 $DESTDIR/lib/modules/7.1.6/build",
	"cp .config $DESTDIR/usr/src/linux-7.1.6/",
	"cp System.map $DESTDIR/boot/System.map-7.1.6",
	"cp .config $DESTDIR/boot/config-7.1.6",
	"cp .config $DESTDIR/var/lib/rad/packages/config/linux"
]
depends = "rsync"
post_install = "depmod -a 7.1.6"
verbose = true
