[package]
name = "linux"
versions = ["6.1.188", "6.12.111", "6.18.53", "7.1.6"]
description = "The Linux package contains the Linux kernel"
sources = ["https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.1.188.tar.xz", "https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.12.111.tar.xz", "https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.18.53.tar.xz", "https://www.kernel.org/pub/linux/kernel/v7.x/linux-7.1.6.tar.xz"]

[build]
system = "manual"
build_commands = [
	"make mrproper",
	"cp /var/lib/rad/packages/config/linux .config",
	"make menuconfig",
	"make -j$RAD_CORES"
]
install_command = [
	"mkdir -p $DESTDIR/boot $DESTDIR/var/lib/rad/packages/config $DESTDIR/usr/src/linux-{version} $DESTDIR/lib/modules/{version}",
	"make modules_install INSTALL_MOD_PATH=$DESTDIR",
	"cp arch/x86/boot/bzImage $DESTDIR/boot/vmlinuz-{version}-radian",
	"make headers_install INSTALL_HDR_PATH=$DESTDIR/usr",
	"cp -r * $DESTDIR/usr/src/linux-{version}/",
	"rm -rf $DESTDIR/lib/modules/{version}/build || true",
	"ln -s /usr/src/linux-{version} $DESTDIR/lib/modules/{version}/build",
	"cp .config $DESTDIR/usr/src/linux-{version}/",
	"cp System.map $DESTDIR/boot/System.map-{version}",
	"cp .config $DESTDIR/boot/config-{version}",
	"cp .config $DESTDIR/var/lib/rad/packages/config/linux"
]
depends = "rsync"
post_install = "depmod -a {version}"
verbose = true
