[package]
name = "rad"
version = "26.10.7"
description = "A utility for managing TOML-format packages of your own repository (source-based)"
source = "https://github.com/dejuri/rad/archive/refs/tags/26.10.7.tar.gz"

[build]
system = "cargo"
