[package]
name = "rad"
version = "26.9.21"
description = "rad is a source-based package manager for Radian GNU/Linux or LFS"
source = "https://github.com/dejuri/rad/archive/refs/tags/26.9.21.tar.gz"

[build]
system = "cargo"
