[package]
name = "libsrtp"
version = "2.8.0"
description = "The libsrtp package provides functions for Secure Realtime Transport Protocol, or SRTP"
source = "https://github.com/cisco/libsrtp/archive/v2.8.0/libsrtp-2.8.0.tar.gz"

[build]
system = "meson"
depends = [
	"nspr",
	"nss"
]
configure_args = [
	"-Dcrypto-library=nss",
	"-Dcrypto-library-kdf=disabled"
]
