[package]
name = "usrsctp"
version = "0.9.5.0"
description = "Portable SCTP userland stack"
source = "https://github.com/sctplab/usrsctp/archive/refs/tags/0.9.5.0.tar.gz"

[build]
system = "manual"
depends = "cmake"
build_commands = [
	"cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Dsctp_build_shared=ON -Dsctp_build_programs=OFF -Dsctp_werror=OFF -DCMAKE_C_FLAGS=\"-std=gnu99 -fPIC -Wno-error -Wno-unterminated-string-initialization -Wno-incompatible-pointer-types\"",
	"cmake --build build -j$RAD_CORES"
]
install_command = "DESTDIR=$DESTDIR cmake --install build"
